version: "3.8"
services:
  traefik:
    image: traefik:v2.4.0
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:3000
    ports:
      - 3000:3000
      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  pingboard-frontend:
    build:
      context: ./
      dockerfile: ./packages/frontend/Dockerfile
    labels:
      traefik.enable: "true"
      traefik.http.routers.pingboard-frontend.entrypoints: web
      traefik.http.routers.pingboard-frontend.rule: PathPrefix(`/`)
      traefik.http.services.pingboard-frontend.loadbalancer.server.port: 80

  pingboard-backend:
    build:
      context: ./
      dockerfile: ./packages/backend/Dockerfile
    environment:
      NODE_ENV: "production"
      COOKIE_KEY: "change me in production!"
      DB_URL: "mysql://pingboard:pingboard@localhost/pingboard"
      SSO_CLIENT_ID:
      SSO_CLIENT_SECRET:
      SSO_REDIRECT_URI: "http://localhost:3000/auth/callback"
      CORE_URL:
      CORE_APP_ID:
      CORE_APP_TOKEN:
    labels:
      traefik.enable: "true"
      traefik.http.routers.pingboard-backend.entrypoints: web
      traefik.http.routers.pingboard-backend.rule: PathPrefix(`/auth`, `/api`)
      traefik.http.services.pingboard-backend.loadbalancer.server.port: 3000

  mariadb:
    image: mariadb:10.6.4-focal
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: "toor"
      MARIADB_DATABASE: "pingboard"
      MARIADB_USER: "pingboard"
      MARIADB_PASSWORD: "pingboard"
