# Based on https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md

name: Backend

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.4.0
        with:
          node-version: '14'
          cache: yarn
      - run: yarn workspaces focus ping-board @ping-board/backend
      - run: yarn workspace @ping-board/backend lint

  build-docker:
    runs-on: ubuntu-18.04
    needs: lint
    if: ${{ startsWith(github.ref, 'refs/tags/') }} # Only run for Tags
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v3.5.0
        with:
          images: ghcr.io/${{ github.repository }}-backend
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./packages/backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.output.labels }}

  build:
    runs-on: ubuntu-18.04
    needs: lint
    if: ${{ startsWith(github.ref, 'refs/tags/') }} # Only run for Tags
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '14'
          cache: yarn

      - name: Install Dependencies
        run: yarn workspaces focus @ping-board/backend

      - name: Build
        run: yarn workspace @ping-board/backend build

      - name: Remove Dev-Dependencies
        run: |
          rm -rf ./.yarn/cache
          rm -rf ./.pnp.cjs
          yarn workspaces focus --production @ping-board/backend

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: backend
          path: |
            .pnp.cjs
            .yarn
            packages/backend/build
            packages/common/build
            LICENSE
